version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres-new-disk
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT}
    networks:
      - db_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - db_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - ${PGADMIN_EXTERNAL_PORT}:${PGADMIN_INTERNAL_PORT}
    networks:
      - db_network

networks:
  db_network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
